/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Employee {
  'id' : string,
  'name' : string,
  'role' : EmployeeRole,
  'companyAssignment' : [] | [string],
  'email' : string,
  'jobTitle' : string,
  'address' : string,
  'onboardingStatus' : OnboardingStatus,
  'contactNumber' : string,
}
export type EmployeeRole = { 'manager' : null } |
  { 'worker' : null };
export interface EmploymentDetails {
  'referenceTaskId' : [] | [string],
  'jobTitle' : string,
  'department' : string,
  'startDate' : Time,
}
export type ExternalBlob = Uint8Array;
export interface Forms {
  'i9' : ExternalBlob,
  'w4' : ExternalBlob,
  'onboarding' : ExternalBlob,
  'identification' : ExternalBlob,
}
export interface Message {
  'content' : string,
  'messageId' : string,
  'relatedTaskId' : [] | [string],
  'messageType' : MessageType,
  'taskId' : [] | [string],
  'timestamp' : Time,
  'recipientId' : string,
  'senderId' : string,
}
export type MessageType = { 'taskRelated' : null } |
  { 'general' : null };
export interface Notification {
  'id' : string,
  'referenceTaskId' : [] | [string],
  'content' : string,
  'taskId' : [] | [string],
  'timestamp' : Time,
  'priority' : NotificationPriority,
  'recipientId' : string,
  'relatedTask' : [] | [Task],
}
export type NotificationPriority = { 'taskRelated' : null } |
  { 'urgent' : null } |
  { 'general' : null };
export interface OnboardingData {
  'forms' : Forms,
  'status' : OnboardingStatus,
  'referenceTaskId' : [] | [string],
  'employeeId' : string,
  'timestamp' : Time,
  'personalInfo' : PersonalInfo,
  'employmentDetails' : EmploymentDetails,
}
export type OnboardingStatus = { 'completed' : null } |
  { 'workInProgress' : null };
export interface PersonalInfo {
  'address' : string,
  'lastName' : string,
  'contactDetails' : string,
  'firstName' : string,
}
export interface Task {
  'id' : string,
  'status' : TaskStatus,
  'title' : string,
  'assignedTo' : string,
  'description' : string,
  'notes' : Array<string>,
  'timestamp' : Time,
  'images' : Array<ExternalBlob>,
}
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'employeeId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkLogEntry {
  'date' : Time,
  'hoursWorked' : number,
  'taskStatus' : TaskStatus,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTaskImage' : ActorMethod<[string, ExternalBlob], undefined>,
  'addTaskNote' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clockIn' : ActorMethod<[string], undefined>,
  'clockOut' : ActorMethod<[string], undefined>,
  'createEmployee' : ActorMethod<[Employee], undefined>,
  'createNotification' : ActorMethod<[Notification], undefined>,
  'createTask' : ActorMethod<[Task], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCountCompletedTasks' : ActorMethod<[string], bigint>,
  'getCountInProgressTasks' : ActorMethod<[string], bigint>,
  'getEmployee' : ActorMethod<[string], Employee>,
  'getMessage' : ActorMethod<[string], Message>,
  'getMessagesForEmployee' : ActorMethod<[string], Array<Message>>,
  'getNotification' : ActorMethod<[string], Notification>,
  'getNotificationsForEmployee' : ActorMethod<[string], Array<Notification>>,
  'getOnboardingData' : ActorMethod<[string], OnboardingData>,
  'getTask' : ActorMethod<[string], Task>,
  'getTasksForEmployee' : ActorMethod<[string], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkLogs' : ActorMethod<[string], Array<WorkLogEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listImages' : ActorMethod<[], Array<ExternalBlob>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Message], undefined>,
  'submitOnboardingData' : ActorMethod<[OnboardingData], undefined>,
  'updateEmployee' : ActorMethod<[string, Employee], undefined>,
  'updateOnboardingStatus' : ActorMethod<[string, OnboardingStatus], undefined>,
  'updateTaskStatus' : ActorMethod<[string, TaskStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];