/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EmployeeRole = IDL.Variant({
  'manager' : IDL.Null,
  'worker' : IDL.Null,
});
export const OnboardingStatus = IDL.Variant({
  'completed' : IDL.Null,
  'workInProgress' : IDL.Null,
});
export const Employee = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'role' : EmployeeRole,
  'companyAssignment' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'jobTitle' : IDL.Text,
  'address' : IDL.Text,
  'onboardingStatus' : OnboardingStatus,
  'contactNumber' : IDL.Text,
});
export const Time = IDL.Int;
export const NotificationPriority = IDL.Variant({
  'taskRelated' : IDL.Null,
  'urgent' : IDL.Null,
  'general' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'assignedTo' : IDL.Text,
  'description' : IDL.Text,
  'notes' : IDL.Vec(IDL.Text),
  'timestamp' : Time,
  'images' : IDL.Vec(ExternalBlob),
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'referenceTaskId' : IDL.Opt(IDL.Text),
  'content' : IDL.Text,
  'taskId' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'priority' : NotificationPriority,
  'recipientId' : IDL.Text,
  'relatedTask' : IDL.Opt(Task),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'employeeId' : IDL.Opt(IDL.Text),
});
export const MessageType = IDL.Variant({
  'taskRelated' : IDL.Null,
  'general' : IDL.Null,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'messageId' : IDL.Text,
  'relatedTaskId' : IDL.Opt(IDL.Text),
  'messageType' : MessageType,
  'taskId' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'recipientId' : IDL.Text,
  'senderId' : IDL.Text,
});
export const Forms = IDL.Record({
  'i9' : ExternalBlob,
  'w4' : ExternalBlob,
  'onboarding' : ExternalBlob,
  'identification' : ExternalBlob,
});
export const PersonalInfo = IDL.Record({
  'address' : IDL.Text,
  'lastName' : IDL.Text,
  'contactDetails' : IDL.Text,
  'firstName' : IDL.Text,
});
export const EmploymentDetails = IDL.Record({
  'referenceTaskId' : IDL.Opt(IDL.Text),
  'jobTitle' : IDL.Text,
  'department' : IDL.Text,
  'startDate' : Time,
});
export const OnboardingData = IDL.Record({
  'forms' : Forms,
  'status' : OnboardingStatus,
  'referenceTaskId' : IDL.Opt(IDL.Text),
  'employeeId' : IDL.Text,
  'timestamp' : Time,
  'personalInfo' : PersonalInfo,
  'employmentDetails' : EmploymentDetails,
});
export const WorkLogEntry = IDL.Record({
  'date' : Time,
  'hoursWorked' : IDL.Float64,
  'taskStatus' : TaskStatus,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTaskImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'addTaskNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clockIn' : IDL.Func([IDL.Text], [], []),
  'clockOut' : IDL.Func([IDL.Text], [], []),
  'createEmployee' : IDL.Func([Employee], [], []),
  'createNotification' : IDL.Func([Notification], [], []),
  'createTask' : IDL.Func([Task], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCountCompletedTasks' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getCountInProgressTasks' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getEmployee' : IDL.Func([IDL.Text], [Employee], []),
  'getMessage' : IDL.Func([IDL.Text], [Message], []),
  'getMessagesForEmployee' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getNotification' : IDL.Func([IDL.Text], [Notification], []),
  'getNotificationsForEmployee' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getOnboardingData' : IDL.Func([IDL.Text], [OnboardingData], []),
  'getTask' : IDL.Func([IDL.Text], [Task], []),
  'getTasksForEmployee' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkLogs' : IDL.Func([IDL.Text], [IDL.Vec(WorkLogEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listImages' : IDL.Func([], [IDL.Vec(ExternalBlob)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([Message], [], []),
  'submitOnboardingData' : IDL.Func([OnboardingData], [], []),
  'updateEmployee' : IDL.Func([IDL.Text, Employee], [], []),
  'updateOnboardingStatus' : IDL.Func([IDL.Text, OnboardingStatus], [], []),
  'updateTaskStatus' : IDL.Func([IDL.Text, TaskStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EmployeeRole = IDL.Variant({
    'manager' : IDL.Null,
    'worker' : IDL.Null,
  });
  const OnboardingStatus = IDL.Variant({
    'completed' : IDL.Null,
    'workInProgress' : IDL.Null,
  });
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'role' : EmployeeRole,
    'companyAssignment' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'jobTitle' : IDL.Text,
    'address' : IDL.Text,
    'onboardingStatus' : OnboardingStatus,
    'contactNumber' : IDL.Text,
  });
  const Time = IDL.Int;
  const NotificationPriority = IDL.Variant({
    'taskRelated' : IDL.Null,
    'urgent' : IDL.Null,
    'general' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'assignedTo' : IDL.Text,
    'description' : IDL.Text,
    'notes' : IDL.Vec(IDL.Text),
    'timestamp' : Time,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'referenceTaskId' : IDL.Opt(IDL.Text),
    'content' : IDL.Text,
    'taskId' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'priority' : NotificationPriority,
    'recipientId' : IDL.Text,
    'relatedTask' : IDL.Opt(Task),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'employeeId' : IDL.Opt(IDL.Text),
  });
  const MessageType = IDL.Variant({
    'taskRelated' : IDL.Null,
    'general' : IDL.Null,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'messageId' : IDL.Text,
    'relatedTaskId' : IDL.Opt(IDL.Text),
    'messageType' : MessageType,
    'taskId' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'recipientId' : IDL.Text,
    'senderId' : IDL.Text,
  });
  const Forms = IDL.Record({
    'i9' : ExternalBlob,
    'w4' : ExternalBlob,
    'onboarding' : ExternalBlob,
    'identification' : ExternalBlob,
  });
  const PersonalInfo = IDL.Record({
    'address' : IDL.Text,
    'lastName' : IDL.Text,
    'contactDetails' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const EmploymentDetails = IDL.Record({
    'referenceTaskId' : IDL.Opt(IDL.Text),
    'jobTitle' : IDL.Text,
    'department' : IDL.Text,
    'startDate' : Time,
  });
  const OnboardingData = IDL.Record({
    'forms' : Forms,
    'status' : OnboardingStatus,
    'referenceTaskId' : IDL.Opt(IDL.Text),
    'employeeId' : IDL.Text,
    'timestamp' : Time,
    'personalInfo' : PersonalInfo,
    'employmentDetails' : EmploymentDetails,
  });
  const WorkLogEntry = IDL.Record({
    'date' : Time,
    'hoursWorked' : IDL.Float64,
    'taskStatus' : TaskStatus,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTaskImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'addTaskNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clockIn' : IDL.Func([IDL.Text], [], []),
    'clockOut' : IDL.Func([IDL.Text], [], []),
    'createEmployee' : IDL.Func([Employee], [], []),
    'createNotification' : IDL.Func([Notification], [], []),
    'createTask' : IDL.Func([Task], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCountCompletedTasks' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getCountInProgressTasks' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getEmployee' : IDL.Func([IDL.Text], [Employee], []),
    'getMessage' : IDL.Func([IDL.Text], [Message], []),
    'getMessagesForEmployee' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getNotification' : IDL.Func([IDL.Text], [Notification], []),
    'getNotificationsForEmployee' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getOnboardingData' : IDL.Func([IDL.Text], [OnboardingData], []),
    'getTask' : IDL.Func([IDL.Text], [Task], []),
    'getTasksForEmployee' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkLogs' : IDL.Func([IDL.Text], [IDL.Vec(WorkLogEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listImages' : IDL.Func([], [IDL.Vec(ExternalBlob)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([Message], [], []),
    'submitOnboardingData' : IDL.Func([OnboardingData], [], []),
    'updateEmployee' : IDL.Func([IDL.Text, Employee], [], []),
    'updateOnboardingStatus' : IDL.Func([IDL.Text, OnboardingStatus], [], []),
    'updateTaskStatus' : IDL.Func([IDL.Text, TaskStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };