/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface OnboardingData {
    forms: Forms;
    status: OnboardingStatus;
    referenceTaskId?: string;
    employeeId: string;
    timestamp: Time;
    personalInfo: PersonalInfo;
    employmentDetails: EmploymentDetails;
}
export interface Forms {
    i9: ExternalBlob;
    w4: ExternalBlob;
    onboarding: ExternalBlob;
    identification: ExternalBlob;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface WorkLogEntry {
    date: Time;
    hoursWorked: number;
    taskStatus: TaskStatus;
}
export interface Task {
    id: string;
    status: TaskStatus;
    title: string;
    assignedTo: string;
    description: string;
    notes: Array<string>;
    timestamp: Time;
    images: Array<ExternalBlob>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PersonalInfo {
    address: string;
    lastName: string;
    contactDetails: string;
    firstName: string;
}
export interface EmploymentDetails {
    referenceTaskId?: string;
    jobTitle: string;
    department: string;
    startDate: Time;
}
export interface Notification {
    id: string;
    referenceTaskId?: string;
    content: string;
    taskId?: string;
    timestamp: Time;
    priority: NotificationPriority;
    recipientId: string;
    relatedTask?: Task;
}
export interface Message {
    content: string;
    messageId: string;
    relatedTaskId?: string;
    messageType: MessageType;
    taskId?: string;
    timestamp: Time;
    recipientId: string;
    senderId: string;
}
export interface Employee {
    id: string;
    name: string;
    role: EmployeeRole;
    companyAssignment?: string;
    email: string;
    jobTitle: string;
    address: string;
    onboardingStatus: OnboardingStatus;
    contactNumber: string;
}
export interface UserProfile {
    name: string;
    email: string;
    employeeId?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum EmployeeRole {
    manager = "manager",
    worker = "worker"
}
export enum MessageType {
    taskRelated = "taskRelated",
    general = "general"
}
export enum NotificationPriority {
    taskRelated = "taskRelated",
    urgent = "urgent",
    general = "general"
}
export enum OnboardingStatus {
    completed = "completed",
    workInProgress = "workInProgress"
}
export enum TaskStatus {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTaskImage(taskId: string, image: ExternalBlob): Promise<void>;
    addTaskNote(taskId: string, note: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clockIn(employeeId: string): Promise<void>;
    clockOut(employeeId: string): Promise<void>;
    createEmployee(employee: Employee): Promise<void>;
    createNotification(notification: Notification): Promise<void>;
    createTask(task: Task): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCountCompletedTasks(employeeId: string): Promise<bigint>;
    getCountInProgressTasks(employeeId: string): Promise<bigint>;
    getEmployee(employeeId: string): Promise<Employee>;
    getMessage(messageId: string): Promise<Message>;
    getMessagesForEmployee(employeeId: string): Promise<Array<Message>>;
    getNotification(notificationId: string): Promise<Notification>;
    getNotificationsForEmployee(employeeId: string): Promise<Array<Notification>>;
    getOnboardingData(employeeId: string): Promise<OnboardingData>;
    getTask(taskId: string): Promise<Task>;
    getTasksForEmployee(employeeId: string): Promise<Array<Task>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkLogs(employeeId: string): Promise<Array<WorkLogEntry>>;
    isCallerAdmin(): Promise<boolean>;
    listImages(): Promise<Array<ExternalBlob>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(message: Message): Promise<void>;
    submitOnboardingData(data: OnboardingData): Promise<void>;
    updateEmployee(employeeId: string, employee: Employee): Promise<void>;
    updateOnboardingStatus(employeeId: string, status: OnboardingStatus): Promise<void>;
    updateTaskStatus(taskId: string, newStatus: TaskStatus): Promise<void>;
}
import type { Employee as _Employee, EmployeeRole as _EmployeeRole, EmploymentDetails as _EmploymentDetails, ExternalBlob as _ExternalBlob, Forms as _Forms, Message as _Message, MessageType as _MessageType, Notification as _Notification, NotificationPriority as _NotificationPriority, OnboardingData as _OnboardingData, OnboardingStatus as _OnboardingStatus, PersonalInfo as _PersonalInfo, Task as _Task, TaskStatus as _TaskStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, WorkLogEntry as _WorkLogEntry, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTaskImage(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTaskImage(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTaskImage(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addTaskNote(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTaskNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTaskNote(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clockIn(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clockIn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clockIn(arg0);
            return result;
        }
    }
    async clockOut(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clockOut(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clockOut(arg0);
            return result;
        }
    }
    async createEmployee(arg0: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployee(to_candid_Employee_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployee(to_candid_Employee_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createNotification(arg0: Notification): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(await to_candid_Notification_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(await to_candid_Notification_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTask(arg0: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(await to_candid_Task_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(await to_candid_Task_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCountCompletedTasks(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCountCompletedTasks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCountCompletedTasks(arg0);
            return result;
        }
    }
    async getCountInProgressTasks(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCountInProgressTasks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCountInProgressTasks(arg0);
            return result;
        }
    }
    async getEmployee(arg0: string): Promise<Employee> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_Employee_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_Employee_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessage(arg0: string): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessage(arg0);
                return from_candid_Message_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessage(arg0);
            return from_candid_Message_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessagesForEmployee(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesForEmployee(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesForEmployee(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotification(arg0: string): Promise<Notification> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotification(arg0);
                return from_candid_Notification_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotification(arg0);
            return from_candid_Notification_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotificationsForEmployee(arg0: string): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationsForEmployee(arg0);
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationsForEmployee(arg0);
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOnboardingData(arg0: string): Promise<OnboardingData> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnboardingData(arg0);
                return from_candid_OnboardingData_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnboardingData(arg0);
            return from_candid_OnboardingData_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: string): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_Task_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_Task_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksForEmployee(arg0: string): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksForEmployee(arg0);
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksForEmployee(arg0);
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkLogs(arg0: string): Promise<Array<WorkLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkLogs(arg0);
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkLogs(arg0);
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listImages(): Promise<Array<ExternalBlob>> {
        if (this.processError) {
            try {
                const result = await this.actor.listImages();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listImages();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n65(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n65(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: Message): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(to_candid_Message_n67(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(to_candid_Message_n67(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitOnboardingData(arg0: OnboardingData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOnboardingData(await to_candid_OnboardingData_n71(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOnboardingData(await to_candid_OnboardingData_n71(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateEmployee(arg0: string, arg1: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, to_candid_Employee_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, to_candid_Employee_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateOnboardingStatus(arg0: string, arg1: OnboardingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOnboardingStatus(arg0, to_candid_OnboardingStatus_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOnboardingStatus(arg0, to_candid_OnboardingStatus_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTaskStatus(arg0: string, arg1: TaskStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_EmployeeRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeRole): EmployeeRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Employee_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Employee {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_EmploymentDetails_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmploymentDetails): EmploymentDetails {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Forms_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Forms): Promise<Forms> {
    return await from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_MessageType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageType): MessageType {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationPriority_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationPriority): NotificationPriority {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
async function from_candid_Notification_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Promise<Notification> {
    return await from_candid_record_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_OnboardingData_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OnboardingData): Promise<OnboardingData> {
    return await from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_OnboardingStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OnboardingStatus): OnboardingStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
async function from_candid_Task_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Promise<Task> {
    return await from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_WorkLogEntry_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkLogEntry): WorkLogEntry {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Promise<Task | null> {
    return value.length === 0 ? null : await from_candid_Task_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    employeeId: [] | [string];
}): {
    name: string;
    email: string;
    employeeId?: string;
} {
    return {
        name: value.name,
        email: value.email,
        employeeId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.employeeId))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    role: _EmployeeRole;
    companyAssignment: [] | [string];
    email: string;
    jobTitle: string;
    address: string;
    onboardingStatus: _OnboardingStatus;
    contactNumber: string;
}): {
    id: string;
    name: string;
    role: EmployeeRole;
    companyAssignment?: string;
    email: string;
    jobTitle: string;
    address: string;
    onboardingStatus: OnboardingStatus;
    contactNumber: string;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_EmployeeRole_n34(_uploadFile, _downloadFile, value.role),
        companyAssignment: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.companyAssignment)),
        email: value.email,
        jobTitle: value.jobTitle,
        address: value.address,
        onboardingStatus: from_candid_OnboardingStatus_n36(_uploadFile, _downloadFile, value.onboardingStatus),
        contactNumber: value.contactNumber
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    messageId: string;
    relatedTaskId: [] | [string];
    messageType: _MessageType;
    taskId: [] | [string];
    timestamp: _Time;
    recipientId: string;
    senderId: string;
}): {
    content: string;
    messageId: string;
    relatedTaskId?: string;
    messageType: MessageType;
    taskId?: string;
    timestamp: Time;
    recipientId: string;
    senderId: string;
} {
    return {
        content: value.content,
        messageId: value.messageId,
        relatedTaskId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.relatedTaskId)),
        messageType: from_candid_MessageType_n40(_uploadFile, _downloadFile, value.messageType),
        taskId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.taskId)),
        timestamp: value.timestamp,
        recipientId: value.recipientId,
        senderId: value.senderId
    };
}
async function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    referenceTaskId: [] | [string];
    content: string;
    taskId: [] | [string];
    timestamp: _Time;
    priority: _NotificationPriority;
    recipientId: string;
    relatedTask: [] | [_Task];
}): Promise<{
    id: string;
    referenceTaskId?: string;
    content: string;
    taskId?: string;
    timestamp: Time;
    priority: NotificationPriority;
    recipientId: string;
    relatedTask?: Task;
}> {
    return {
        id: value.id,
        referenceTaskId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.referenceTaskId)),
        content: value.content,
        taskId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.taskId)),
        timestamp: value.timestamp,
        priority: from_candid_NotificationPriority_n45(_uploadFile, _downloadFile, value.priority),
        recipientId: value.recipientId,
        relatedTask: record_opt_to_undefined(await from_candid_opt_n47(_uploadFile, _downloadFile, value.relatedTask))
    };
}
async function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TaskStatus;
    title: string;
    assignedTo: string;
    description: string;
    notes: Array<string>;
    timestamp: _Time;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    status: TaskStatus;
    title: string;
    assignedTo: string;
    description: string;
    notes: Array<string>;
    timestamp: Time;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n50(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assignedTo: value.assignedTo,
        description: value.description,
        notes: value.notes,
        timestamp: value.timestamp,
        images: await from_candid_vec_n52(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    forms: _Forms;
    status: _OnboardingStatus;
    referenceTaskId: [] | [string];
    employeeId: string;
    timestamp: _Time;
    personalInfo: _PersonalInfo;
    employmentDetails: _EmploymentDetails;
}): Promise<{
    forms: Forms;
    status: OnboardingStatus;
    referenceTaskId?: string;
    employeeId: string;
    timestamp: Time;
    personalInfo: PersonalInfo;
    employmentDetails: EmploymentDetails;
}> {
    return {
        forms: await from_candid_Forms_n57(_uploadFile, _downloadFile, value.forms),
        status: from_candid_OnboardingStatus_n36(_uploadFile, _downloadFile, value.status),
        referenceTaskId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.referenceTaskId)),
        employeeId: value.employeeId,
        timestamp: value.timestamp,
        personalInfo: value.personalInfo,
        employmentDetails: from_candid_EmploymentDetails_n59(_uploadFile, _downloadFile, value.employmentDetails)
    };
}
async function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    i9: _ExternalBlob;
    w4: _ExternalBlob;
    onboarding: _ExternalBlob;
    identification: _ExternalBlob;
}): Promise<{
    i9: ExternalBlob;
    w4: ExternalBlob;
    onboarding: ExternalBlob;
    identification: ExternalBlob;
}> {
    return {
        i9: await from_candid_ExternalBlob_n53(_uploadFile, _downloadFile, value.i9),
        w4: await from_candid_ExternalBlob_n53(_uploadFile, _downloadFile, value.w4),
        onboarding: await from_candid_ExternalBlob_n53(_uploadFile, _downloadFile, value.onboarding),
        identification: await from_candid_ExternalBlob_n53(_uploadFile, _downloadFile, value.identification)
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referenceTaskId: [] | [string];
    jobTitle: string;
    department: string;
    startDate: _Time;
}): {
    referenceTaskId?: string;
    jobTitle: string;
    department: string;
    startDate: Time;
} {
    return {
        referenceTaskId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.referenceTaskId)),
        jobTitle: value.jobTitle,
        department: value.department,
        startDate: value.startDate
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: _Time;
    hoursWorked: number;
    taskStatus: _TaskStatus;
}): {
    date: Time;
    hoursWorked: number;
    taskStatus: TaskStatus;
} {
    return {
        date: value.date,
        hoursWorked: value.hoursWorked,
        taskStatus: from_candid_TaskStatus_n50(_uploadFile, _downloadFile, value.taskStatus)
    };
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    worker: null;
}): EmployeeRole {
    return "manager" in value ? EmployeeRole.manager : "worker" in value ? EmployeeRole.worker : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    workInProgress: null;
}): OnboardingStatus {
    return "completed" in value ? OnboardingStatus.completed : "workInProgress" in value ? OnboardingStatus.workInProgress : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taskRelated: null;
} | {
    general: null;
}): MessageType {
    return "taskRelated" in value ? MessageType.taskRelated : "general" in value ? MessageType.general : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taskRelated: null;
} | {
    urgent: null;
} | {
    general: null;
}): NotificationPriority {
    return "taskRelated" in value ? NotificationPriority.taskRelated : "urgent" in value ? NotificationPriority.urgent : "general" in value ? NotificationPriority.general : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "pending" in value ? TaskStatus.pending : "completed" in value ? TaskStatus.completed : "inProgress" in value ? TaskStatus.inProgress : value;
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n38(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n53(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Promise<Array<Notification>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Notification_n43(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Promise<Array<Task>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Task_n48(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkLogEntry>): Array<WorkLogEntry> {
    return value.map((x)=>from_candid_WorkLogEntry_n63(_uploadFile, _downloadFile, x));
}
function to_candid_EmployeeRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeRole): _EmployeeRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Employee_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Employee): _Employee {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_EmploymentDetails_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentDetails): _EmploymentDetails {
    return to_candid_record_n76(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_Forms_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Forms): Promise<_Forms> {
    return await to_candid_record_n74(_uploadFile, _downloadFile, value);
}
function to_candid_MessageType_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): _MessageType {
    return to_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function to_candid_Message_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Message): _Message {
    return to_candid_record_n68(_uploadFile, _downloadFile, value);
}
function to_candid_NotificationPriority_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationPriority): _NotificationPriority {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
async function to_candid_Notification_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Notification): Promise<_Notification> {
    return await to_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function to_candid_OnboardingData_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OnboardingData): Promise<_OnboardingData> {
    return await to_candid_record_n72(_uploadFile, _downloadFile, value);
}
function to_candid_OnboardingStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OnboardingStatus): _OnboardingStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function to_candid_Task_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): Promise<_Task> {
    return await to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n66(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    role: EmployeeRole;
    companyAssignment?: string;
    email: string;
    jobTitle: string;
    address: string;
    onboardingStatus: OnboardingStatus;
    contactNumber: string;
}): {
    id: string;
    name: string;
    role: _EmployeeRole;
    companyAssignment: [] | [string];
    email: string;
    jobTitle: string;
    address: string;
    onboardingStatus: _OnboardingStatus;
    contactNumber: string;
} {
    return {
        id: value.id,
        name: value.name,
        role: to_candid_EmployeeRole_n13(_uploadFile, _downloadFile, value.role),
        companyAssignment: value.companyAssignment ? candid_some(value.companyAssignment) : candid_none(),
        email: value.email,
        jobTitle: value.jobTitle,
        address: value.address,
        onboardingStatus: to_candid_OnboardingStatus_n15(_uploadFile, _downloadFile, value.onboardingStatus),
        contactNumber: value.contactNumber
    };
}
async function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    referenceTaskId?: string;
    content: string;
    taskId?: string;
    timestamp: Time;
    priority: NotificationPriority;
    recipientId: string;
    relatedTask?: Task;
}): Promise<{
    id: string;
    referenceTaskId: [] | [string];
    content: string;
    taskId: [] | [string];
    timestamp: _Time;
    priority: _NotificationPriority;
    recipientId: string;
    relatedTask: [] | [_Task];
}> {
    return {
        id: value.id,
        referenceTaskId: value.referenceTaskId ? candid_some(value.referenceTaskId) : candid_none(),
        content: value.content,
        taskId: value.taskId ? candid_some(value.taskId) : candid_none(),
        timestamp: value.timestamp,
        priority: to_candid_NotificationPriority_n19(_uploadFile, _downloadFile, value.priority),
        recipientId: value.recipientId,
        relatedTask: value.relatedTask ? candid_some(await to_candid_Task_n21(_uploadFile, _downloadFile, value.relatedTask)) : candid_none()
    };
}
async function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: TaskStatus;
    title: string;
    assignedTo: string;
    description: string;
    notes: Array<string>;
    timestamp: Time;
    images: Array<ExternalBlob>;
}): Promise<{
    id: string;
    status: _TaskStatus;
    title: string;
    assignedTo: string;
    description: string;
    notes: Array<string>;
    timestamp: _Time;
    images: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        status: to_candid_TaskStatus_n23(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assignedTo: value.assignedTo,
        description: value.description,
        notes: value.notes,
        timestamp: value.timestamp,
        images: await to_candid_vec_n25(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    employeeId?: string;
}): {
    name: string;
    email: string;
    employeeId: [] | [string];
} {
    return {
        name: value.name,
        email: value.email,
        employeeId: value.employeeId ? candid_some(value.employeeId) : candid_none()
    };
}
function to_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    messageId: string;
    relatedTaskId?: string;
    messageType: MessageType;
    taskId?: string;
    timestamp: Time;
    recipientId: string;
    senderId: string;
}): {
    content: string;
    messageId: string;
    relatedTaskId: [] | [string];
    messageType: _MessageType;
    taskId: [] | [string];
    timestamp: _Time;
    recipientId: string;
    senderId: string;
} {
    return {
        content: value.content,
        messageId: value.messageId,
        relatedTaskId: value.relatedTaskId ? candid_some(value.relatedTaskId) : candid_none(),
        messageType: to_candid_MessageType_n69(_uploadFile, _downloadFile, value.messageType),
        taskId: value.taskId ? candid_some(value.taskId) : candid_none(),
        timestamp: value.timestamp,
        recipientId: value.recipientId,
        senderId: value.senderId
    };
}
async function to_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    forms: Forms;
    status: OnboardingStatus;
    referenceTaskId?: string;
    employeeId: string;
    timestamp: Time;
    personalInfo: PersonalInfo;
    employmentDetails: EmploymentDetails;
}): Promise<{
    forms: _Forms;
    status: _OnboardingStatus;
    referenceTaskId: [] | [string];
    employeeId: string;
    timestamp: _Time;
    personalInfo: _PersonalInfo;
    employmentDetails: _EmploymentDetails;
}> {
    return {
        forms: await to_candid_Forms_n73(_uploadFile, _downloadFile, value.forms),
        status: to_candid_OnboardingStatus_n15(_uploadFile, _downloadFile, value.status),
        referenceTaskId: value.referenceTaskId ? candid_some(value.referenceTaskId) : candid_none(),
        employeeId: value.employeeId,
        timestamp: value.timestamp,
        personalInfo: value.personalInfo,
        employmentDetails: to_candid_EmploymentDetails_n75(_uploadFile, _downloadFile, value.employmentDetails)
    };
}
async function to_candid_record_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    i9: ExternalBlob;
    w4: ExternalBlob;
    onboarding: ExternalBlob;
    identification: ExternalBlob;
}): Promise<{
    i9: _ExternalBlob;
    w4: _ExternalBlob;
    onboarding: _ExternalBlob;
    identification: _ExternalBlob;
}> {
    return {
        i9: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.i9),
        w4: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.w4),
        onboarding: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.onboarding),
        identification: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.identification)
    };
}
function to_candid_record_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referenceTaskId?: string;
    jobTitle: string;
    department: string;
    startDate: Time;
}): {
    referenceTaskId: [] | [string];
    jobTitle: string;
    department: string;
    startDate: _Time;
} {
    return {
        referenceTaskId: value.referenceTaskId ? candid_some(value.referenceTaskId) : candid_none(),
        jobTitle: value.jobTitle,
        department: value.department,
        startDate: value.startDate
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeRole): {
    manager: null;
} | {
    worker: null;
} {
    return value == EmployeeRole.manager ? {
        manager: null
    } : value == EmployeeRole.worker ? {
        worker: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OnboardingStatus): {
    completed: null;
} | {
    workInProgress: null;
} {
    return value == OnboardingStatus.completed ? {
        completed: null
    } : value == OnboardingStatus.workInProgress ? {
        workInProgress: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationPriority): {
    taskRelated: null;
} | {
    urgent: null;
} | {
    general: null;
} {
    return value == NotificationPriority.taskRelated ? {
        taskRelated: null
    } : value == NotificationPriority.urgent ? {
        urgent: null
    } : value == NotificationPriority.general ? {
        general: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == TaskStatus.pending ? {
        pending: null
    } : value == TaskStatus.completed ? {
        completed: null
    } : value == TaskStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): {
    taskRelated: null;
} | {
    general: null;
} {
    return value == MessageType.taskRelated ? {
        taskRelated: null
    } : value == MessageType.general ? {
        general: null
    } : value;
}
async function to_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
